src/Game/DLC/aoc2.cpp
src/Game/DLC/aoc2.h
src/KingSystem/ActorSystem/CMakeLists.txt
src/KingSystem/ActorSystem/actActor.h
src/KingSystem/ActorSystem/actActorParamMgr.h
src/KingSystem/ActorSystem/actLifeRecoveryInfo.h
src/KingSystem/CMakeLists.txt
src/KingSystem/Damage/CMakeLists.txt
src/KingSystem/Damage/dmgDamageCallback.h
src/KingSystem/Damage/dmgDamageInfoManager.h
src/KingSystem/Damage/dmgDamageManagerBase.cpp
src/KingSystem/Damage/dmgDamageManagerBase.h
src/KingSystem/Damage/dmgStruct20.cpp
src/KingSystem/Damage/dmgStruct20.h

Also added some temporary classes/variables used by DamageManagerBase.

ksys/dmg: Implementing some of DamageManagerBase. 

---

src/KingSystem/Event/CMakeLists.txt
src/KingSystem/Event/evtEvent.cpp
src/KingSystem/Event/evtEvent.h
src/KingSystem/Event/evtManager.h
src/KingSystem/Event/evtOrderParam.cpp
src/KingSystem/Event/evtOrderParam.h
workflow.sh

uninitialize is matched, 6 others are WIP

evt::OrderParam Functions

---

src/Game/AI/Action/actionCurseRRematchCount.cpp
src/Game/AI/Action/actionCurseRRematchCount.h
src/Game/AI/Query/queryCheckCurseRRetryEverOnce.cpp

Everything matches, no further issues.

uking/action and uking/query: Action and Query related to ChampionBallad added

---

src/KingSystem/ActorSystem/actDebug.h
src/KingSystem/Resource/resModelResourceDivide.cpp

All functions match, no further issues.

ksys/res: Add ModelResourceDivide

---

src/KingSystem/System/CMakeLists.txt
src/KingSystem/System/MemoryProfiler.cpp
src/KingSystem/System/MemoryProfiler.h

pretty empty, so perhaps nulled

MemoryProfiler done

---

src/KingSystem/Physics/CMakeLists.txt
src/KingSystem/Physics/System/physRagdollControllerKeyList.cpp
src/KingSystem/Physics/System/physRagdollControllerKeyList.h

All functions match, no further issues in this part.

ksys/phys: Add RagdollControllerKeyList-Resource

---

Contributing.md
tools/rename_functions_in_ida.py
tools/util/utils.py

I am not 100% sure that everything has been converted correctly, nor that the scripts have all been modified to reflect these changes.
The script used for conversion is as follows:
```python3
import csv
prefixes = ("sub_")
good_prefixes = ("eco::", "ui::")
last_addr = 0
with open("data/ukf.csv", "r") as csvfile, open("data/uking_functions.csv", "w") as f:
w = csv.writer(f)
w.writerow(["Address", "Quality", "Size", "Name"])
for row in csv.reader(csvfile):
addr = row[0].strip()
ida_name = row[1].strip()
if not ida_name.startswith(good_prefixes) and "sub" in ida_name.lower() and "nullsub" not in ida_name.lower() and ida_name.lower().endswith(addr[-10:].lower()):
if not ida_name.lower().startswith("sub"):
print(ida_name)
assert False
ida_name = ""
name = ida_name
size = …
```

CSV formatting improvements

---

src/KingSystem/Resource/Actor/resResourceAnimInfo.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/53)

Fix warning

---

.gitignore
tools/ghidra_scripts/RenameFunctionsInGhidra.java

The Ghidra import script will do automatic demangling, and will set tags based on the decompilation status of the function.
If run multiple times it will update the tags and function names as they are changed.
I also plan to release a script that will import DWARF information and potentially RTTI, once I am satisfied with it. (in another PR)
~~I also added a fix for a build warning~~, and added Ghidra's `*.lock` files to the `.gitignore`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/52)

Ghidra function import script

---

tools/viking/src/functions.rs
tools/viking/src/tools/check.rs

This brings functionality up to what diff.py uses
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/54)

Added support for WIP function status

---

src/KingSystem/Physics/CMakeLists.txt
src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp
src/KingSystem/Physics/SupportBone/physSupportBoneResource.h
src/KingSystem/Physics/SupportBone/physSupportBoneResourceMainBone.cpp

Quite a lot of mismatches here...
1. `SupportBoneResource::init`: Mismatches in the creation part of `connectionCurveList`
2. `SupportBoneResource::doSomethingAboutConnectionCurves` (maybe also `someHelperInterpolationForConnectionCurvesSomething`): Float operations being picky about the order of commands
3. `SupportBoneResource::BaseBone::postRead_`: Due to seadQuat::normalize() mismatch, this function does not match.
Other notes:
- `.gitmodules` was updated to point to my (updated) `sead` library. When everything matches, a PR can be made there and the original repo used instead.
- Functions should obviously still be renamed to match their functionality
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Support bone resource

---

src/KingSystem/System/CMakeLists.txt
src/KingSystem/System/SystemTimers.cpp
src/KingSystem/System/SystemTimers.h

All functions match perfectly. The member variable names could be improved to better reflect their functionality, but I don't know enough about their usage to properly describe them in their names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/57)

ksys: Add SystemTimers

---

src/KingSystem/Framework/GameConfig.h
src/KingSystem/Resource/resResourceArchive.h
src/KingSystem/Resource/resResourceMgrTask.cpp
src/KingSystem/Resource/resResourceMgrTask.h
src/KingSystem/Resource/resSystem.cpp
src/KingSystem/Resource/resSystem.h
src/KingSystem/System/CMakeLists.txt
src/KingSystem/System/StarterPackMgr.cpp
src/KingSystem/System/StarterPackMgr.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/60)

StarterPackMgr

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/62)

readme: Explain why 1.6.0 is not being decompiled

---

src/KingSystem/System/CMakeLists.txt
src/KingSystem/System/MessageCapture.cpp
src/KingSystem/System/MessageCapture.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/64)

Implement MessageCapture

---

Contributing.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/66)

Make class ordering more clear

---

src/KingSystem/Map/CMakeLists.txt
src/KingSystem/Map/mapLazyTraverseList.cpp
src/KingSystem/Map/mapLazyTraverseList.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/65)

Implement LazyTraverseList

---

src/KingSystem/Resource/Actor/resResourceAttCheck.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/71)

ksys/res: utilize the negate operator

---

Contributing.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/73)

contributing: Clarify Trello and clang-format usage

---

src/KingSystem/CMakeLists.txt
src/KingSystem/ksysDebugInput.cpp
src/KingSystem/ksysDebugInput.h

Add ksysDebugInput Singleton
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/74)

Add ksysDebugInput Singleton

---

docs/doxygen_config.py

(by @notyourav)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/77)

docs: Indent header items

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/78)

Update README.md to include xdelta

---

src/KingSystem/Map/mapPlacementActors.h
src/KingSystem/Map/mapPlacementMap.cpp
src/KingSystem/Map/mapPlacementMap.h
src/KingSystem/Physics/StaticCompound/physStaticCompound.h

Added some initial functions to PlacementMap
There are some changes to associated classes:
- PlacementActors
- StaticCompound
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/79)

Add initial PlacementMap functions

---

src/KingSystem/Map/mapObject.h
src/KingSystem/Map/mapPlacementActors.h
src/KingSystem/Map/mapPlacementMap.cpp
src/KingSystem/Map/mapPlacementMap.h
src/KingSystem/Map/mapPlacementMapMgr.h
src/KingSystem/Map/mapPlacementMgr.h
src/KingSystem/Physics/StaticCompound/physStaticCompound.h
src/KingSystem/System/CMakeLists.txt
src/KingSystem/System/Patrol.cpp
src/KingSystem/System/Patrol.h

Added more PlacementMap functions
- loadStaticMap_
- parseStaticMap
- loadDynamicMap
- parseDynamicMap
- x_6
- cleanupPhysics
- loadStaticCompound
- x_2
- doSomethingStaticCompound (was cleanHkscMaybe)
- isDynamicLoaded ( at 7100d43f18 )
- doDisableObjStaticCompound
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/80)

More PlacementMap functions

---

src/KingSystem/ActorSystem/LOD/actLodState.cpp
src/KingSystem/Map/CMakeLists.txt
src/KingSystem/Map/mapLazyTraverseList.h
src/KingSystem/Map/mapPlacementActors.h
src/KingSystem/Map/mapPlacementAreaMgr.cpp
src/KingSystem/Map/mapPlacementAreaMgr.h
src/KingSystem/Map/mapStagePreActorCache.h
src/KingSystem/Utils/MathUtil.h

~~Requies open-ead/sead#96~~
Should be squashed before merging
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/81)

PlacementStruct1

---

src/KingSystem/Utils/CMakeLists.txt
src/KingSystem/Utils/Thread/LowPrioThreadMgr.cpp
src/KingSystem/Utils/Thread/LowPrioThreadMgr.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/82)

LowPrioThreadMgr

---

src/Game/UI/uiPauseMenuDataMgr.cpp
src/Game/UI/uiPauseMenuDataMgr.h

Added 
- `PauseMenuDataMgr::equipWeapon()`
- `PauseMenuDataMgr::unequp()`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/86)

Match two small functions in PauseMenuDataMgr

---

src/Game/UI/uiPauseMenuDataMgr.cpp
src/Game/UI/uiPauseMenuDataMgr.h

Add PauseMenuDataMgr::x_28
Note: Types are incorrect
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/87)

Add PauseMenuDataMgr::x_28 - types are incorrect

---

src/Game/CMakeLists.txt
src/Game/UI/uiPauseMenuDataMgr.cpp
src/Game/UI/uiPauseMenuDataMgr.h
src/Game/gameItemUtils.cpp
src/Game/gameItemUtils.h

Add `PauseMenuDataMgr::grabbedItemStuff()`
This needs a better name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/88)

Add PauseMenuDataMgr::grabbedItemStuff()

---

src/KingSystem/Ecosystem/ecoLevelSensor.cpp

implemented calculatePoints going to continue scaleWeapon and scaleActor
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/90)

ksys::eco::LevelSensor::calculatePoints

---

src/Game/AI/Action/actionAddAutoPlacementCreator.cpp
src/Game/AI/Action/actionAddAutoPlacementCreator.h
src/KingSystem/ActorSystem/actActor.h
src/KingSystem/ActorSystem/actPhysicsUserTag.h
src/KingSystem/Map/CMakeLists.txt
src/KingSystem/Map/mapAutoPlacement.cpp
src/KingSystem/Map/mapAutoPlacement.h
src/KingSystem/Map/mapAutoPlacementFlowMgr.cpp
src/KingSystem/Map/mapAutoPlacementFlowMgr.h
src/KingSystem/Map/mapAutoPlacementMgr.cpp
src/KingSystem/Map/mapAutoPlacementMgr.h
src/KingSystem/Map/mapDebug.cpp
src/KingSystem/Map/mapDebug.h
src/KingSystem/Utils/MathUtil.h
src/KingSystem/World/worldWeatherMgr.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/91)

auto placement work

---

src/KingSystem/Framework/CMakeLists.txt
src/KingSystem/Framework/Framework.cpp
src/KingSystem/Framework/Framework.h
src/KingSystem/Sound/CMakeLists.txt
src/KingSystem/Sound/sndMgr.cpp
src/KingSystem/Sound/sndMgr.h
src/KingSystem/System/ProductReporter.cpp
src/KingSystem/System/ProductReporter.h
src/KingSystem/System/VFR.h

Some very minor differences left in ProductReporter::incrementSceneAndRomWorkTime (as a result of my imperfect member function-ification). It should be functionally equivalent, at least.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/93)

ksys::ProductReporter

---

src/KingSystem/System/ProductReporter.cpp
src/KingSystem/System/ProductReporter.h

Switch ProductReporter::incrementSceneAndRomWorkTime to using lambdas

---

src/KingSystem/System/CMakeLists.txt
src/KingSystem/System/Hio.cpp
src/KingSystem/System/Hio.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/95)

ksys: Add Hio

---

src/KingSystem/Framework/GameConfig.h
src/KingSystem/System/CMakeLists.txt
src/KingSystem/System/Patrol.cpp
src/KingSystem/System/Patrol.h
src/KingSystem/System/StarterPackMgr.cpp
src/KingSystem/System/Terminal.cpp
src/KingSystem/System/Terminal.h

(Modified GameConfig as well)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/96)

Implement ksys::Patrol & ksys::Terminal

---

src/KingSystem/ActorSystem/actInfoData.cpp
src/KingSystem/World/worldDefines.h
src/KingSystem/World/worldManager.cpp
src/KingSystem/World/worldManager.h
src/KingSystem/World/worldTimeMgr.h
src/KingSystem/World/worldWeatherMgr.cpp
src/KingSystem/World/worldWeatherMgr.h

- Added `WeatherMgr::rollNewWeather`
- Changed `WeatherType` to `u8`
- Changed 1st arg of `Manager::setWeatherType` to `u32`
- Changed 1st arg of `Manager::getWeatherTypeString` to `u32`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/100)

Added WeatherMgr::rollNewWeather

---

.gitignore
src/Game/CMakeLists.txt
src/Game/E3MGR.cpp
src/Game/E3MGR.hpp
src/Game/E3Mgr.cpp
src/Game/E3Mgr.h
src/Game/E3Mgr.hpp
src/KingSystem/Map/mapPlacementMgr.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/101)

Decompile most of E3mgr

---

src/KingSystem/System/CMakeLists.txt
src/KingSystem/System/NXArgs.cpp
src/KingSystem/System/NXArgs.h

This adds a header for NXArgs and implements 2 functions from the subsystem. One function, nxargs::handleArgs, is blocked currently.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/105)

Add NXArgs

---

lib/hkStubs/CMakeLists.txt
lib/hkStubs/Havok/Geometry/Internal/Types/hkcdVertex.h
src/KingSystem/Physics/RigidBody/Shape/CharacterPrism/physCharacterPrismShape.cpp
src/KingSystem/Physics/RigidBody/Shape/CharacterPrism/physCharacterPrismShape.h
src/KingSystem/Physics/RigidBody/Shape/Polytope/physPolytopeShape.h
src/KingSystem/Physics/RigidBody/Shape/physShapeParamObj.cpp
src/KingSystem/Physics/physMaterialMask.h

- Implemented `CharacterPrismShape`
- Also added `hkcdVertex` implementation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/106)

Implement ksys::phys::CharacterPrismShape class

---

src/KingSystem/Physics/RigidBody/TeraMesh/physTeraMeshRigidBody.cpp
src/KingSystem/Physics/RigidBody/TeraMesh/physTeraMeshRigidBody.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/107)

Implement TeraMeshRigidBody class

---

CMakeLists.txt
lib/gsys/include/gsys/gsysModelNW.h
src/KingSystem/System/NXArgs.cpp

Creating this to not lose these files, this pr will also handle updating nnheaders once open-ead/nnheaders#12 is merged
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/108)

Handle nn::gfx merge

---

src/Game/UI/CMakeLists.txt
src/Game/UI/uiFadeProgress.cpp
src/Game/UI/uiFadeProgress.h
src/Game/UI/uiUtils.h

Any comments or improvements are highly appreciated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/110)

Implemented FadeProgress class

---

.gitignore

**Updating uking_functions.csv to replace unmangled name with mangled name**
Doing a small change now to test if this breaks anything, etc.
I also upgraded NintendoSDK submodule in the process. Let me know if I should revert that.
**Testing**
Did `tools/check` and it said ok
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/115)

Updating CSV

---

src/KingSystem/World/worldShootingStarMgr.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/114)

Matched ShootingStarMgr::initSchedule

---

data/status_ai.yml
src/Game/AI/AI/aiActorWaterDepthSelect.cpp
src/Game/AI/AI/aiActorWaterDepthSelect.h
src/KingSystem/ActorSystem/actActor.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/117)

Add uking::ai::ActorWaterDepthSelect functions

---

src/KingSystem/Map/mapRail.cpp
src/KingSystem/Map/mapRail.h
src/KingSystem/System/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/118)

mapRail.cpp ok

---

src/KingSystem/Resource/CMakeLists.txt
src/KingSystem/Resource/resPlacement.cpp
src/KingSystem/Resource/resPlacement.h

First project PR, hopefully I followed the right standards.
Adds the ksys::res::Placement class. I do think I'm missing two functions, but working on adding them and wanted feedback on where this was right now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/120)

resPlacement

---

src/KingSystem/Map/mapPlacementMgr.cpp
src/KingSystem/System/SystemTimers.cpp
src/KingSystem/System/Timer.cpp
src/KingSystem/System/VFR.cpp
src/KingSystem/System/VFR.h
src/KingSystem/System/VFRValue.cpp
src/KingSystem/World/worldEnvMgr.cpp
src/KingSystem/World/worldTimeMgr.cpp
src/KingSystem/ksysDebugInput.cpp

Added `VFR::getDeltaFrame` and used that instead of `VFR::getDeltaTime`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/122)

Added VFR::getDeltaFrame

---

src/Game/UI/uiPauseMenuDataMgr.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/138)

match PMDM autoEquip and unequipAll

---

src/KingSystem/ActorSystem/actActorCreator.cpp
src/KingSystem/ActorSystem/actInstParamPack.h
src/KingSystem/World/worldShootingStarMgr.cpp

Tested with the CPEAM PR and seems to work. These should be enough get #141 unblocked.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/143)

Add initial version of at-param helpers

---

.gitmodules

Take the `sead::TaskBase` changes from https://github.com/open-ead/sead/pull/212
Also adding a `branch` key to `.gitmodules` so libs can be updated with one command with magoo ![](https://raw.githubusercontent.com/Pistonite/magoo/main/magoo.webp)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldaret/botw/150)

chore: update libs
